name: codecov
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    codecov:
        name: py${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        env:
            MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.11"]
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
            - name: Generate coverage report
              run: |
                pip install pytest pytest-cov
                pytest --cov=./ --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
              with:
                files: ./coverage.xml
                fail_ci_if_error: true
